#!/usr/bin/env python37
# -*- coding: utf-8 -*-
#@File  : oswf.py
#@Author: Frank
#@Date  : 11/9/18

import os

path = '/home/frank/'

def oswf(path):
	for root, dirs, files in os.walk(path):
		for file in files:
			yield os.path.join(root,file)
		for dir in dirs:
			oswf(os.path.join(root,dir))

for i in oswf(path):
	print(i)
